### ISSUE TITLE
Rerunning the role fails after changing Grafana admin credentials

### ISSUE THREAD

**Issue by myllynen** [linux-system-roles/metrics#26]
After running the role, logging in to Grafana (thus changing the password), the role fails:

TASK [rhel-system-roles.metrics : Ensure graphing service runtime settings are configured] ************************************************************************************************************************
fatal: [localhost]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content": "{\"message\":\"Invalid username or password\"}", "content_length": "42", "content_type": "application/json; charset=UTF-8", "date": "Mon, 16 Nov 2020 09:33:25 GMT", "elapsed": 0, "expires": "-1", "json": {"message": "Invalid username or password"}, "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized", "pragma": "no-cache", "redirected": false, "status": 401, "url": "http://admin:admin@localhost:3000/api/plugins/performancecopilot-pcp-app/settings", "x_frame_options": "deny"}

While the check is probably helpful initially I think the role should handle somehow the case where Grafana has been used already to allow rerunning the role. Thanks.

**Comment by andreasgerstmayr** [comment]
This issue will be fixed in an elegant way [1] once the latest Grafana is packaged - then we don't need to call the Grafana API, which requires the Grafana admin user credentials.

Not sure what we should do about the current version. Silently ignore 401 Unauthroized errors? Check if some file which gets created during startup of Grafana is already present?

[1] https://grafana.com/docs/grafana/latest/administration/provisioning/#plugins

**Comment by natoscott** [comment]
> This issue will be fixed in an elegant way [1] once the latest Grafana is packaged - then we don't need to call the Grafana API, which requires the Grafana admin user credentials.
> 
> Not sure what we should do about the current version.

Since its the change in authentication credentials on first login, we could update the role to allow these to be passed in (to override those default admin/admin settings), I guess.

@myllynen your "(thus changing the password)" wording above implies the credentials are always changed, but I believe there is a 'skip' option (or words to that effect) that allows bypassing the 'requirement' to change admin credentials - i.e. its not mandatory.

**Comment by myllynen** [comment]
Hmm, 'skip' option might be helpful, however I don't see it (or something similar) mentioned in the README, perhaps could be checked at some point if it exists then would be added to the README? Thanks.

**Comment by natoscott** [comment]
@myllynen sorry, I was unclear - the 'skip' option is in the Grafana UI on the first-login screen where its prompting you to change the password.  Its a little tick box just below the text entry field from memory.

**Comment by myllynen** [comment]
Ok, now I see what you mean. Yes, that would avoid this issue but I hope most people will want to change a default password. In any case, I don't think this is a show-stopper for anyone but ideally the playbooks could avoid failure even after a password change. Thanks.

**Comment by natoscott** [comment]
This was fixed (using the technique Andreas described) in ansible-pcp a little while back, and is resolved here by #98
